package associacao.classes;

/*
 * TRABALHANDO COM ASSOCIAÇÃO DE CLASSES 
 * A CLASSE DEPARTAMENTO POSSUINDO UMA RELAÇÃO 
 * COM A CLASSE PESSOA INFORMANDO UM VALOR PRIVATE 
 * COMO ATRIBUTO ARRAY DENTRO DA CLASSE DEPARTAMENTO 
 * 
 */
public class Departamento {
	private Pessoa[] pessoas;	
}
