package exception.teste;

/*
* EXCESSOES SÃO COMO CLASSES É PERTECEM A CLASSE TROWHABLE
* EXCESSOES SÃO FLUXOS ANORMAIS QUE APARECEM MAIS NÃO DEVERIA
* ACONTECER NO SEU CODIGO.
* 
* OBS1: CLASSE ERRO → UMA AÇÃO INESPERADA DO CODIGO MAIS NÃO PODE SER TRATADA.
* OBS2: CLASSE EXCEPTION → DUAS PALAVARAS CHAVES PARA A CLASSE CHECKED / UNCHECKED.
* OBS3: CLASSE EXCEPTION CHECKED → SÃO EXCECOES ONDE VOCE PRECISA CRIAR UM TRATAMENTO PARA 
* AS EXECUCOES POIS A PROPRIA JVM JÁ ESTARÁ PREVIAMENTE ESPERANDO O TRATAMENTO CASO O CONTRARIO 
* O CODIGO NÃO SERÁ COMPILADO.(EXCEÇOES ESPECIASI FORA DO CONTROLE DO PRGRAMADOR)
* OBS4: CLASSE EXCEPTION UNCHECKED → SÃO EXCECÕES ONDE NÃO PRECISA DE TRATAMENTOS
* (EXCEÇÕES DENTRO DO CONTROLE DO PROGRAMADOR).
* CLASSE RUNTIMEEXCEPTION E SUBCLASSES ABAIXO → EXCEPTION CONSIDERADAS UNCHECKED.
* CLASSE EXCEPTION E SUBCLASSES DIRETAS DA MESMA → EXCEPTION CONSIDERADAS CHECKED.
* 
* 
* 
* 
*/

public class ErroTeste {

	public static void main(String[] args) {
		stackOverFlowErro();

	}
	
	public static void stackOverFlowErro() {
		stackOverFlowErro();
		
		
	}

}
