package Classe;

public class ImprimindoVariaveis {

	public static void main(String[] args) {
		// IMPRIMINDO DADOS EM TELA 
		// STRIBUINDO VALORES A VARIAVEIS
		
		/*
		 * TIPO INT => TIPO NUMERO INTEIRO
		 * TIPO BOOLEAN => TIPO VALORES BOOLEANOS TRUE / FALSE
		 * TIPO FLOAT => TIPO VALORES FLUTUANTES OU REAIS 
		 * TIPO STRING => TIPO TEXTOS OU PALAVRAS 
		 * TIPO CHAR => TIPOS CARACTERES (SO ACEITA UM UNICO CARACTER POR VARIAVEL)
		 */
		
		/*
		 * OPERADORES
		 * ++ => INCREMENTO
		 * -- => DECREMENTO
		 * + => OPERADOR DE MAIS
		 * - => OPERADOR DE MENOS
		 * * => OPERADOR DE MULTIPLICAÇÃO
		 / => OPERADOR DE DIVISÃO 
		 * () => OPERADOR DE CAST
		 * ! => OPERADOR DE NEGAÇÃO
		 */
		
		
		// PARA INICIALIZAR UMA VARIAVEL UTILIZA O SINAL DE "=" COM O VALOR DESEJADO
		int idade = 10;
		
		//REALIZANDO CONCATENAÇÃO DE VARIAVEIS E STRING 
		System.out.println("Dados Impressos na tela é : " + idade);
		
		
	}

}
