package polimorfismo.classes;

/*
 * TRABALHANDO COM POLIMORFISMO USANDO ORIENTAÇÃO A INTERFACES 
 * E POSSIVEL TAMBEM TRABALHR COM ARRAY LIST PARA GRANDES QUANTIDADES DE DADOS.
 * É POSSIVEL TRABALHAR COM ARRAYS USANDO ORIENTACAO A INTERFACES DEVIDO 
 * A CODIGOS MAIS ACESSIVEIS PARA MANUTENÇÃO.
 */

public interface GenericDAO {
	public abstract void save();

}
